### ISSUE TITLE
ObjectRecognition:  Obtain model information from a proper location

### ISSUE THREAD

**Issue by fhcarter** [Vantiq/vantiq-extension-sources#108]
Currently stored in an anonymous dropbox -- move it to a more official/supported place.

**Comment by liu-xiao-guo** [comment]
In China, we cannot access the .mov and yolo.pb file. Every time, I have to download the file and copy to the correct location to make it successfully built. Yes, it is definitely needed to move a public place

**Comment by fhcarter** [comment]
@liu-xiao-guo Chances are, these will move to an S3 bucket.  Is that better?

**Comment by liu-xiao-guo** [comment]
As long as it is accessible to the developers, I think it should be fine. thanks
