### ISSUE TITLE
Adding Modbus extension support

### ISSUE THREAD

**Issue by liu-xiao-guo** [Vantiq/vantiq-extension-sources#114]
We have an existing project requiring modbus support. Currently, we use NodeRED to as a middleware to connect to Vantiq platform. This may not be so obvious to developer using  our Vantiq platform. I am going to visit another agricultural company which also uses modbus as a way to communicate to the cloud. Can we officially support modbus extensions source?

Thanks & best regards.

**Comment by fhcarter** [comment]
See `EasyModbusSource`
