### ISSUE TITLE
JDBC: DateTime elements are not returned correctly

### ISSUE THREAD

**Issue by namirfa** [Vantiq/vantiq-extension-sources#139]
When querying for DateTime elements, the data is returned incorrectly. Seems like the SimpleDateFormat being used to parse the retrieved data is bad.

**Comment by rblumer4** [comment]
email about issue:
-----------------
From: Xiaoguo Liu <xliu@vantiq.com>
Sent: Thursday, February 28, 2019 2:08 AM
To: Technical Team; Namir Fawaz
Subject: Reading DateTime from MySQL databse incorrectly using the JDBC connector 
 
Hi,
 
Today, I just tried to read a date time defined in my MySQL database using our JDBC connector. I initialize it in either of the following way in the MySQL database:
 
INSERT INTO system_plan VALUES
("BJ-C1-201902011145", "Plan001", "基础开工", "2019-5-30 00:00:00", "Plan002", "主体结构施工至正负零", "2019-7-30 00:00:00");
 
INSERT INTO system_plan VALUES
("BJ-C1-201902011145", "Plan001", "基础开工", "2019-5-30", "Plan002", "主体结构施工至正负零", "2019-7-30");
 
I checked it correctly shown in the MySql database:
 
mysql> select * from system_plan
    -> ;
+--------------------+-------------+---------------+---------------------+-------------+----------------------+---------------------+
| ID                 | 管控节点ID1 | 管控节点名称1 | 管控节点计划时间1   | 管控节点ID2 | 管控节点名称2        | 管控节点计划时间2   |
+--------------------+-------------+---------------+---------------------+-------------+----------------------+---------------------+
| BJ-C1-201902011145 | Plan001     | 基础开工      | 2019-05-30 00:00:00 | Plan002     | 主体结构施工至正负零 | 2019-07-30 00:00:00 |
+--------------------+-------------+---------------+---------------------+-------------+----------------------+---------------------+
1 row in set (0.00 sec)
 
However, when I read it inside our Vantiq platform and show it in a topic, it is something like:
 
{
  "管控节点名称1": "基础开工",
   "管控节点ID1": "Plan001",
   "管控节点计划时间1": "2019-30-00T08:00:00.000+0800",
   "管控节点ID2": "Plan002",
   "管控节点计划时间2": "2019-30-00T08:00:00.000+0800",
   "管控节点名称2": "主体结构施工至正负零",
   "ID": "BJ-C1-201902011145"
}
 
From above, you can see that the time is totally not what I want. I cannot even save it into a type. 
The date shows:
 
**"2019-30-00T08:00:00.000+0800"**
 
How can I read the DateTime correctly inside our database.
 
Thanks & best regards,
XiaoGuo
