### ISSUE TITLE
Adding more tokens for JDBC connector

### ISSUE THREAD

**Issue by liu-xiao-guo** [Vantiq/vantiq-extension-sources#173]
We have an elevator project INESA.  It connects different elevators companies, and each of the them runs in a different namespaces. All of them need to write to the same database. Currently, our JDBC configuration file is like:

authToken=Fa_clVu87ywx0FcceFgouyXSS9ed7H_gqEQ85R1sAvg=
sources=StudentDb,SuccessDb,SystemPlan,SystemEngineering
targetServer=https://dev.vantiq.cn/

It only supports one token with multiple sources. I think it would be good to support multiple tokens, which support multiple namespaces so that each of the namespaces can write to the same database.

If we cannot support multiple tokens, we have to run multiple instances of the JDBC connectors, which makes it harder for use.

Thanks & best regards,
XiaoGuo

**Comment by fhcarter** [comment]
The basic VANTIQ model for data isolation per-namespace (with more details possible within that).  As such, this would create a number of potential issues.  

If you feel it important to consider in the future, please add to Aha.
