### ISSUE TITLE
Check for slashes when building/pushing images with gradle

### ISSUE THREAD

**Issue by namirfa** [Vantiq/vantiq-extension-sources#231]
We don't protect against missing "/" when creating the full `registry/namespace/repository:tag` definition to build and push the connector images.

We should check for their existence, and add them if not included.

**Comment by fhcarter** [comment]
I would just add the slashes in, then, after doing that, do a replace('//', '/').  That handles it & is much less complex than checking.

That is

```
fullrepo = reg + '/' + pathTo + '/' + reponame
fullrepo = fullrepo.replace('//', '/')
```

**Comment by namirfa** [comment]
@fhcarter 

Sounds good, changing the PR now.
