### ISSUE TITLE
Could not GET vantiq-sdk from bintray

### ISSUE THREAD

**Issue by fujitake** [Vantiq/vantiq-extension-sources#257]
I’m facing below error during compile jdbcSource that seems related to Bintray service has now been sunset, according to [Bintray](https://bintray.com/). Please guide me how to get vantiq-sdk instead of Bintray/JCenter.

Error message of ./gradlew jdbcSource:assemble is as follows:

```
ubuntu@ip-172-31-38-144:~/extsrc/vantiq-extension-sources$ ./gradlew jdbcSource:assemble
 
> Configure project :
The property "dockerRegistryPassword" was not provided. This may affect publish operations.
 
> Task :jdbcSource:compileJava FAILED
 
FAILURE: Build failed with an exception.
 
* What went wrong:
Execution failed for task ':jdbcSource:compileJava'.
> Could not resolve all files for configuration ':jdbcSource:compileClasspath'.
   > Could not resolve io.vantiq:vantiq-sdk:1.0.17.
     Required by:
         project :jdbcSource
      > Could not resolve io.vantiq:vantiq-sdk:1.0.17.
         > Could not get resource 'https://dl.bintray.com/vantiq/maven/io/vantiq/vantiq-sdk/1.0.17/vantiq-sdk-1.0.17.pom'.
            > Could not GET 'https://dl.bintray.com/vantiq/maven/io/vantiq/vantiq-sdk/1.0.17/vantiq-sdk-1.0.17.pom'. Received status code 403 from server: Forbidden
 
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
 
* Get more help at https://help.gradle.org
 
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.0/userguide/command_line_interface.html#sec:command_line_warnings
 
BUILD FAILED in 6s
3 actionable tasks: 1 executed, 2 up-to-date
```

**Comment by namirfa** [comment]
@fujitake Fuijitake-san,

We are working on a permanent solution to the Bintray issue, and will be migrating the `vantiq-sdk-java` jar to a new host in the coming days.

In the meantime, you should be able to remove or comment the Vantiq Java SDK compile dependency in the JDBC Connector's `build.gradle` file (line 78). This library is only included in the JDBC connector for testing purposes, so removing it will mean that some tests will fail if you choose to run them. So long as you are only running `./gradlew assemble`, you should not see any of the tests getting run. 

We will close this issue once we have migrated the jar file.
