### ISSUE TITLE
ObjRec: Add option to include the image as a base64 string content to the payload instead of file

### ISSUE THREAD

**Issue by pburma** [Vantiq/vantiq-extension-sources#317]
Would like an option to include the image file content in the payload itself as a base64 encoded string which can be used directory in HTML img tags <img src="<img.content>". 

@bruden01 created his own one-off that does this but it would be nice to have a flag we could set with the image options where instead of vantiq, local, both we can also do inline or something like that to put the image content into the payload.

**Comment by fhcarter** [comment]
Current plan:  Add `includeEncodedImage` config param & query param.  If set, Base64 encode image will be included in the results sent/returned Vantiq.  This parameter will be orthogonal to the `saveImage` config property/query param in that you can include the B64 encoding and/or save the image.  Or one or the other.

So the option will be there, but not _instead_ of [saving the] file.

**Comment by fhcarter** [comment]
Added `includeEncodedImage` config/request option to the configuration & query parameters.  When set to true, the connector will return a property (`encodedImage`) when sending results.  This parameter is orthogonal to the saving of images.  You can set either or both.

The returned image is, however, affected by changes you may request for the image.  So if, for example, you ask to label the image, the returned, encoded image will be labeled.

Note, too, that when running a query, you'll need to set `sendFullResponse` to get the encoded image returned.

`includeEncodedImage` is available for both the YoloProcessor and the NoProcessor.

See the README for more details.
