### ISSUE TITLE
CamelConnector cannot open a routes file when running under Windows

### ISSUE THREAD

**Issue by pburma** [Vantiq/vantiq-extension-sources#370]
Attempting to test the CamelConnector and was unable to get it to load a routes file. I am guessing this is Windows specific but it might be an issue on my end, I attached my connector build (just the bin dir otherwise its too big).

The reason I am guessing this is a Windows issue is it doesn't look like anyone has tried to run this on a Windows system before as the .bat file that gets created doesn't work either. I had to run the java command directory to execute. However, the same problem occurs when running the bash version using the Ubuntu wslv2 Linux subsystem on Windows, which actually suggests its maybe not Windows specific unless its a low level OS/API problem. 

My source definition is: 

    {
       "camelRuntime": {
         "appName": "file",
         "routesDocument": "routes.yml"
       },
      "general": {
      }
    }

I have tried every permutation of the file path that I can think of, and also tried switching from yml to xml. The yml and xml are just the sample ones provided in the documentation or in the salesforce example. The errors are: 

[ttps://internal.vantiq.com/...] ionWebSocketListener#CamelFile INFO  WebSocket open
[ttps://internal.vantiq.com/...] ionWebSocketListener#CamelFile INFO  Successful connection to CamelFile
[ttps://internal.vantiq.com/...] CamelHandleConfiguration       ERROR Cannot fetch document: routes.yml: [io.vantiq.resource.not.found: The requested instance ('{name=routes.yml}') of the documents resource could not be found.]
[ttps://internal.vantiq.com/...] CamelHandleConfiguration       ERROR Camel connector operation requires a valid route specification. No document 'routes.yml' was found.

And with the different path settings in the src config they are similar: 
> ERROR Camel connector operation requires a valid route specification. No document 'd:/routes.xml' was found.
ERROR Camel connector operation requires a valid route specification. No document 'd://routes.xml' was found.
ERROR Camel connector operation requires a valid route specification. No document 'D:/routes.yml' was found.
ERROR Camel connector operation requires a valid route specification. No document '.\routes.xml' was found
ERROR Camel connector operation requires a valid route specification. No document '. (this one was for .\routes.xml, the above was .\\routes.xml)
ERROR Camel connector operation requires a valid route specification. No document 'D:\vantiq\repos\vantiq-extension-sources\camelConnector\build\distributions\camelConnector\camelConnector\bin\routes.yml' was found.

And this is how I am running the java app: 
`"%JAVA_HOME%\bin\java" -classpath ..\lib\*;..\logCongif\* io.vantiq.extsrc.camelconn.connector.CamelMain`

[CamelConnector-bin.zip](https://github.com/Vantiq/vantiq-extension-sources/files/11092246/CamelConnector-bin.zip)

.
.
For Linux , this is redundant so I moved it to the bottom here

This is the run command, no need to manually do things here the shell script works fine....
`./camelConnector server.config`

> [ttps://internal.vantiq.com/...] ionWebSocketListener#CamelFile INFO  WebSocket open
[ttps://internal.vantiq.com/...] ionWebSocketListener#CamelFile INFO  Successful connection to CamelFile
[ttps://internal.vantiq.com/...] CamelHandleConfiguration       ERROR Cannot fetch document: /mnt/d/vantiq/repos/vantiq-extension-sources/camelConnector/build/distributions/camelConnector/camelConnector/bin/routes.xml: [io.vantiq.resource.not.found: The requested instance ('{name=mnt/d/vantiq/repos/vantiq-extension-sources/camelConnector/build/distributions/camelConnector/camelConnector/bin/routes.xml}') of the documents resource could not be found.]
[ttps://internal.vantiq.com/...] CamelHandleConfiguration       ERROR Camel connector operation requires a valid route specification. No document '/mnt/d/vantiq/repos/vantiq-extension-sources/camelConnector/build/distributions/camelConnector/camelConnector/bin/routes.xml' was found.
[ttps://internal.vantiq.com/...] CamelCore                      INFO  Reconnect message received. Reinitializing configuration
[ttps://internal.vantiq.com/...] ionWebSocketListener#CamelFile INFO  Successful connection to CamelFile
[kJoinPool.commonPool-worker-51] CamelCore                      INFO  Reconnect ran with success value: true
[ttps://internal.vantiq.com/...] CamelHandleConfiguration       ERROR Cannot fetch document: /mnt/d/vantiq/repos/vantiq-extension-sources/camelConnector/build/distributions/camelConnector/camelConnector/bin/routes.yml: [io.vantiq.resource.not.found: The requested instance ('{name=mnt/d/vantiq/repos/vantiq-extension-sources/camelConnector/build/distributions/camelConnector/camelConnector/bin/routes.yml}') of the documents resource could not be found.]
[ttps://internal.vantiq.com/...] CamelHandleConfiguration       ERROR Camel connector operation requires a valid route specification. No document '/mnt/d/vantiq/repos/vantiq-extension-sources/camelConnector/build/distributions/camelConnector/camelConnector/bin/routes.yml' was found.
[ttps://internal.vantiq.com/...] CamelCore                      INFO  Reconnect message received. Reinitializing configuration
[ttps://internal.vantiq.com/...] ionWebSocketListener#CamelFile ERROR Map of the received message: {status=400, contentType=application/json, body=[{code=io.vantiq.sourcemgr.source.noConnectionLocal, message=The CONNECT_EXTENSION operation on data source br_sandbox:CamelFile did not complete successfully: The data source br_sandbox:CamelFile does not have an associated stream service.  Please contact Vantiq support., params=[br_sandbox:CamelFile, The data source br_sandbox:CamelFile does not have an associated stream service.  Please contact Vantiq support.]}]}
[ttps://internal.vantiq.com/...] ionWebSocketListener#CamelFile WARN  Error occurred attempting to connect to source.
[kJoinPool.commonPool-worker-51] nsionWebSocketClient#CamelFile WARN  Retrying connection (count: 0) due to hitting reactivation window
[ttps://internal.vantiq.com/...] ionWebSocketListener#CamelFile INFO  Successful connection to CamelFile
[kJoinPool.commonPool-worker-51] CamelCore                      INFO  Reconnect ran with success value: true
[ttps://internal.vantiq.com/...] CamelHandleConfiguration       ERROR Cannot fetch document: routes.yml: [io.vantiq.resource.not.found: The requested instance ('{name=routes.yml}') of the documents resource could not be found.]

**Comment by fhcarter** [comment]
I may be misunderstanding things.  The `routesDocument` config parameter should refer to a Vantiq Document, not a file on the host machine.  As per the log,

> CamelHandleConfiguration ERROR Cannot fetch document: routes.yml: [io.vantiq.resource.not.found: The requested instance ('{name=routes.yml}') of the documents resource could not be found.]

We don't have a way directly to read from a file on the host machine.

**Comment by fhcarter** [comment]
BTW -- please report the failure in the `camelConnector.bat` file.

**Comment by pburma** [comment]
This is my bad then, I didn't understand that the document needed to be uploaded into Vantiq, I just assumed it was a local file like the server.config, I was expecting it to be referenced similar to how model files are in the objecRec source.

**Comment by fhcarter** [comment]
@pburma Happy to figure out how to make it clearer.  The `README.md` file current says something like:

**routesDocument** -- the name of a Vantiq Document containing the XML or YAML definition of the routes to run. The format of the document (XML or YAML) will be determined from the file name (_e.g._, `routes.xml`)

Suggestions for alternate wording are welcome.

**Comment by pburma** [comment]
The documentation is fine I think, this is my error but if you wanted to you could add something about "uploading" a routes file to vantiq documents store.
