### ISSUE TITLE
camelConnector build creates a seemingly invalid windows bat file that does not run

### ISSUE THREAD

**Issue by pburma** [Vantiq/vantiq-extension-sources#371]
After doing a clean gradle build of the camelConnector I cannot run the windows bat file that is built. I can open an Ubuntu shell and run the shell script no problem, I can also just run the java command manually and that works, I suspect there is a typo in the file somewhere (see attached). 

[camelConnector.txt](https://github.com/Vantiq/vantiq-extension-sources/files/11092896/camelConnector.txt)

Here is the error: 

> \>  camelConnector.bat  server.config
The input line is too long.
The syntax of the command is incorrect.

**Comment by rblumer4** [comment]
*Workaround:*  copy the camelconnector distribution to a directory that is shorter in length, then run the command from there.
For example, if I unzip the **camelConnector .zip** file to `c:/temp/camel` and then run the bat file from there, it avoids the _line too long_ error:
```
C:\temp\camel\camelConnector\bin\camelConnector.bat server.config
--or--
cd C:\temp\camel\camelConnector\bin
.\camelConnector.bat server.config
```
