### ISSUE TITLE
jdbcSource throws error after being up for a few hours

### ISSUE THREAD

**Issue by bruden01** [Vantiq/vantiq-extension-sources#87]
Having run the source for a few hours, I can back and executed one of my procedures.

It through the error below.  Afrer restarting it it worked again.
```
HTTP Status 400 (Bad Request) executing Procedure sql.demo:

com.accessg2.ag2rs.streams.source.not_found: The EXTENSION source JDBC1 (namespace brett) has no associated session for operation publish. (MID: be23b16d-cfe7-4426-b360-d98592d8bdfa)
```

**Comment by namirfa** [comment]
I have tried replicating this by running the source for both 2 and 3 hours, and then trying to publish/select from it. So far, I have no been able to reproduce this issue.

**Comment by fhcarter** [comment]
I think the addition of `sendPings` in the configuration fixed this.  Closing for now
