### ISSUE TITLE
ObjectRecognition: can't tell what image goes with what source

### ISSUE THREAD

**Issue by bruden01** [Vantiq/vantiq-extension-sources#91]
When a message is received from the object recognition source it looks like

```
{
   "timestamp": 1544324954272,
   "results": [
      {
         "confidence": 0.87103534,
         "location": {
            "top": -13.647221,
            "left": -121.504875,
            "bottom": 447.84503,
            "right": 547.24585
         },
         "label": "person"
      }
   ],
   "dataSource": {},
   "neuralNet": {}
}
```

... when the source  config is set to save images they are stored in VANTIQ and locallly under a name like ` 2018-12-09--10-22-54.jpg`

With multiple image sources it will be difficult to know which image  goes with which source.  Ideally we should add the image name to the json object so we know which one to get if we want to display it.

**Comment by bruden01** [comment]
also, it would be ideal, rather than just being written to docs if they wound up in a folder structure like

objectRecognition/<source name>/<timestamp>.jpg

**Comment by namirfa** [comment]
@bruden01 
I had a few questions regarding this.

1) Is it sufficient to just add the source name to the json object, or would you like the option to add the name as a prefix/suffix to the image filename.

2) When adding the folder structure to the docs, do you simply want to add an "objectRecognition" folder, which contains all the images from all your sources.

OR

Would you want to have a global "objectRecognition" folder, and then subfolders under that directory with the name of a given source.

**Comment by namirfa** [comment]
Additional features as requested by Brett:

1) Change filename to include source name, e.g. objectRecognition/mySource/2018-12-17--14-57-47.jpg

2) Add filename as part of the JSON Data sent back to VANTIQ
